### ISSUE TITLE
Support for mentions and hashtags in tweets

### ISSUE THREAD

**Issue by ClydeDz** [zorapeteri/react-tweet-card#1]
Hi, @zorapeteri,

Thanks for developing this npm package. It's super easy to use and exactly what I was looking for. I must also add that [this](https://zorapeteri.github.io/react-tweet-card/) is probably the most comprehensive and intentional documentation sites I've seen in a long time, so great work on that! 

While integrating this, I noticed that the Tweet card doesn't automatically highlight @mentions and #hashtags like a real tweet would, as pictured below. Do I need to enable this using any particular configuration? 

![image](https://user-images.githubusercontent.com/13506613/174792143-d0381eeb-2f9c-458a-9350-37fa1eb6909e.png)

Thanks!

**Comment by zorapeteri** [comment]
Hey @ClydeDz

Thanks a bunch for spotting this bug!
I've fixed it and published a new version of the package, please let me know if it resolved the issue for you

**Comment by ClydeDz** [comment]
Thank you, @zorapeteri. I can confirm that it works now and the links are clickable as well. 

![image](https://user-images.githubusercontent.com/13506613/175471377-7cc26c18-d981-477c-97c2-63ca147e8c14.png)
