### ISSUE TITLE
Tweet header is clickable when clickableProfileLink is set to false

### ISSUE THREAD

**Issue by ClydeDz** [zorapeteri/react-tweet-card#2]
Hi, again,

I noticed that when setting clickableProfileLink to false (or leaving it out as the default), the profile image, name, username and Twitter logo still remains clickable, as pictured below. When I click on it, it just opens the same site in another tab. This can be tested [here](https://clydedz.github.io/tweet-to-image/). 

![image](https://user-images.githubusercontent.com/13506613/175471750-e840d0f7-3df6-4cc1-b480-53d3d505af18.png)
      
I believe it's because even after setting it to false, the elements are still wrapped in the `a` tag, only without any `href`.

![image](https://user-images.githubusercontent.com/13506613/175471727-478bfb01-3c83-4814-a3e2-c5b2ad41115f.png)

Thanks!

**Comment by zorapeteri** [comment]
Hey @ClydeDz, thanks for the catch, I've fixed this and released it in 0.1.9

**Comment by ClydeDz** [comment]
Thank you, @zorapeteri. I can confirm that it's fixed for the profile image, name, and username. However, the Twitter logo is still clickable. Is that expected?

![image](https://user-images.githubusercontent.com/13506613/175795157-3fe29c53-0b1b-4bad-a5bf-a17dd54f3cd8.png)

**Comment by zorapeteri** [comment]
The Twitter logo will always act as a link to Twitter by design.
If in your use case you don't want anything on the tweet card to be clickable, I advise you set a `pointer-events: none` CSS rule to `.react-tweet-card__container` or the className you provide to the component

**Comment by ClydeDz** [comment]
A link to Twitter or the specific tweet? Because if it's a link to the Twitter site in general, I wouldn't mind it here. In that case, the href should default to Twitter.com? `pointer-events: none` does the trick, but I want hashtags and mentions to be clickable.

**Comment by zorapeteri** [comment]
Good point! The Twitter logo was supposed to be a link to the `permalink` if provided. It seems it was the same issue with the `href` tag being empty instead of being completely omitted. Both should be fixed in 0.2.0, if you omit the `permalink` prop the twitter logo will simply be an image and not a link

**Comment by ClydeDz** [comment]
Sweet, I gave it a go and can confirm that it's working as expected now.
