### ISSUE TITLE
Error when trying to use the package: document is not defined

### ISSUE THREAD

**Issue by pedrolzoliveira** [zorapeteri/react-tweet-card#3]
When I try to add a tweet to my next project it throws a error to me

![image](https://user-images.githubusercontent.com/48186206/197315830-2f6351f1-3039-4ef4-bc39-b58f5fd67cc1.png)

**Comment by zorapeteri** [comment]
Hi Pedro! Are you trying to server-side render the component? In that case, if you're using Next, you have to do something like this: (or find a way for the library that you're using to render client-side-only components)


```
import dynamic from 'next/dynamic'

const TweetCard = dynamic(
  () => import('react-tweet-card'),
  { ssr: false }
)

export default TweetCard;
```

**Comment by pedrolzoliveira** [comment]
It worked, thanks!

I wasn't trying to server side render the component, unless next tries that automatically... either way, thank u!
